name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Action 
        uses: actions/hello-world-javascript-action@v1
        # try to reference a version or a specific..... commitID
        with:
          who-to-greet: Aeriel
      
      - name: Log Greeting Time
        run: echo "${{ steps.Simple_JS_Action.outputs.time }}"

   
