name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:20-alpine3.18
    # image: node:20-alpine3.18
    # ports:
    # volumes:
    # options: --cpus 1 --host
    steps:
      - name: Log node version
        run: |
          node -v 
          cat /etc/os-release